-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mult_hw is
generic (
    C_M_AXI_GMEM_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_BUSER_WIDTH : INTEGER := 1;
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_CACHE_VALUE : INTEGER := 3 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_AWREADY : IN STD_LOGIC;
    m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem_WVALID : OUT STD_LOGIC;
    m_axi_gmem_WREADY : IN STD_LOGIC;
    m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem_WLAST : OUT STD_LOGIC;
    m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_WUSER_WIDTH-1 downto 0);
    m_axi_gmem_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_ARREADY : IN STD_LOGIC;
    m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem_RVALID : IN STD_LOGIC;
    m_axi_gmem_RREADY : OUT STD_LOGIC;
    m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_RLAST : IN STD_LOGIC;
    m_axi_gmem_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_RUSER_WIDTH-1 downto 0);
    m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BVALID : IN STD_LOGIC;
    m_axi_gmem_BREADY : OUT STD_LOGIC;
    m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_BUSER_WIDTH-1 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of mult_hw is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "mult_hw_mult_hw,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu200-fsgd2104-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=392,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1994,HLS_SYN_LUT=3293,HLS_VERSION=2022_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (12 downto 0) := "0000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (12 downto 0) := "0000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (12 downto 0) := "0000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (12 downto 0) := "0000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (12 downto 0) := "0000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (12 downto 0) := "0000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (12 downto 0) := "0001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (12 downto 0) := "0010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (12 downto 0) := "0100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant C_M_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal in1 : STD_LOGIC_VECTOR (63 downto 0);
    signal in2 : STD_LOGIC_VECTOR (63 downto 0);
    signal out_r : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem_blk_n_AW : STD_LOGIC;
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal gmem_blk_n_B : STD_LOGIC;
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal in2_read_reg_172 : STD_LOGIC_VECTOR (63 downto 0);
    signal in1_read_reg_177 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln19_fu_143_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln19_reg_182 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln26_fu_148_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln26_reg_187 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln2_reg_192 : STD_LOGIC_VECTOR (61 downto 0);
    signal A_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal A_V_ce0 : STD_LOGIC;
    signal A_V_we0 : STD_LOGIC;
    signal A_V_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal A_V_ce1 : STD_LOGIC;
    signal A_V_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal A_V_ce2 : STD_LOGIC;
    signal A_V_q2 : STD_LOGIC_VECTOR (7 downto 0);
    signal A_V_ce3 : STD_LOGIC;
    signal A_V_q3 : STD_LOGIC_VECTOR (7 downto 0);
    signal B_V_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal B_V_ce0 : STD_LOGIC;
    signal B_V_we0 : STD_LOGIC;
    signal B_V_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal B_V_ce1 : STD_LOGIC;
    signal B_V_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal B_V_ce2 : STD_LOGIC;
    signal B_V_q2 : STD_LOGIC_VECTOR (7 downto 0);
    signal B_V_ce3 : STD_LOGIC;
    signal B_V_q3 : STD_LOGIC_VECTOR (7 downto 0);
    signal C_V_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal C_V_ce0 : STD_LOGIC;
    signal C_V_we0 : STD_LOGIC;
    signal C_V_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_start : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_done : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_idle : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_ready : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWVALID : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_WVALID : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_WLAST : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARVALID : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_RREADY : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_BREADY : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_ce0 : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_we0 : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_start : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_done : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_idle : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_ready : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWVALID : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_WVALID : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_WLAST : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARVALID : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_RREADY : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_BREADY : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_ce0 : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_we0 : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_start : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_done : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_idle : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_ready : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce0 : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce1 : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_address2 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce2 : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_address3 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce3 : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce0 : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_address1 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce1 : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_address2 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce2 : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_address3 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce3 : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_ce0 : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_we0 : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_d0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_start : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_done : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_idle : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_ready : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWVALID : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WVALID : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WLAST : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARVALID : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_RREADY : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_BREADY : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_C_V_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_C_V_ce0 : STD_LOGIC;
    signal gmem_AWVALID : STD_LOGIC;
    signal gmem_AWREADY : STD_LOGIC;
    signal gmem_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_WVALID : STD_LOGIC;
    signal gmem_WREADY : STD_LOGIC;
    signal gmem_ARVALID : STD_LOGIC;
    signal gmem_ARREADY : STD_LOGIC;
    signal gmem_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_RVALID : STD_LOGIC;
    signal gmem_RREADY : STD_LOGIC;
    signal gmem_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_RFIFONUM : STD_LOGIC_VECTOR (8 downto 0);
    signal gmem_BVALID : STD_LOGIC;
    signal gmem_BREADY : STD_LOGIC;
    signal grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal sext_ln42_fu_162_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component mult_hw_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_AWREADY : IN STD_LOGIC;
        m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WVALID : OUT STD_LOGIC;
        m_axi_gmem_WREADY : IN STD_LOGIC;
        m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_WLAST : OUT STD_LOGIC;
        m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_ARREADY : IN STD_LOGIC;
        m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RVALID : IN STD_LOGIC;
        m_axi_gmem_RREADY : OUT STD_LOGIC;
        m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_RLAST : IN STD_LOGIC;
        m_axi_gmem_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BVALID : IN STD_LOGIC;
        m_axi_gmem_BREADY : OUT STD_LOGIC;
        m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        A_V_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        A_V_ce0 : OUT STD_LOGIC;
        A_V_we0 : OUT STD_LOGIC;
        A_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        in1 : IN STD_LOGIC_VECTOR (63 downto 0);
        trunc_ln : IN STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component mult_hw_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_AWREADY : IN STD_LOGIC;
        m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WVALID : OUT STD_LOGIC;
        m_axi_gmem_WREADY : IN STD_LOGIC;
        m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_WLAST : OUT STD_LOGIC;
        m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_ARREADY : IN STD_LOGIC;
        m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RVALID : IN STD_LOGIC;
        m_axi_gmem_RREADY : OUT STD_LOGIC;
        m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_RLAST : IN STD_LOGIC;
        m_axi_gmem_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BVALID : IN STD_LOGIC;
        m_axi_gmem_BREADY : OUT STD_LOGIC;
        m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        B_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        B_V_ce0 : OUT STD_LOGIC;
        B_V_we0 : OUT STD_LOGIC;
        B_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        in2 : IN STD_LOGIC_VECTOR (63 downto 0);
        trunc_ln1 : IN STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component mult_hw_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        A_V_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        A_V_ce0 : OUT STD_LOGIC;
        A_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        A_V_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        A_V_ce1 : OUT STD_LOGIC;
        A_V_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        A_V_address2 : OUT STD_LOGIC_VECTOR (4 downto 0);
        A_V_ce2 : OUT STD_LOGIC;
        A_V_q2 : IN STD_LOGIC_VECTOR (7 downto 0);
        A_V_address3 : OUT STD_LOGIC_VECTOR (4 downto 0);
        A_V_ce3 : OUT STD_LOGIC;
        A_V_q3 : IN STD_LOGIC_VECTOR (7 downto 0);
        B_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        B_V_ce0 : OUT STD_LOGIC;
        B_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        B_V_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
        B_V_ce1 : OUT STD_LOGIC;
        B_V_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        B_V_address2 : OUT STD_LOGIC_VECTOR (5 downto 0);
        B_V_ce2 : OUT STD_LOGIC;
        B_V_q2 : IN STD_LOGIC_VECTOR (7 downto 0);
        B_V_address3 : OUT STD_LOGIC_VECTOR (5 downto 0);
        B_V_ce3 : OUT STD_LOGIC;
        B_V_q3 : IN STD_LOGIC_VECTOR (7 downto 0);
        C_V_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        C_V_ce0 : OUT STD_LOGIC;
        C_V_we0 : OUT STD_LOGIC;
        C_V_d0 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component mult_hw_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_AWREADY : IN STD_LOGIC;
        m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WVALID : OUT STD_LOGIC;
        m_axi_gmem_WREADY : IN STD_LOGIC;
        m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_WLAST : OUT STD_LOGIC;
        m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_ARREADY : IN STD_LOGIC;
        m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RVALID : IN STD_LOGIC;
        m_axi_gmem_RREADY : OUT STD_LOGIC;
        m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_RLAST : IN STD_LOGIC;
        m_axi_gmem_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BVALID : IN STD_LOGIC;
        m_axi_gmem_BREADY : OUT STD_LOGIC;
        m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        sext_ln42 : IN STD_LOGIC_VECTOR (61 downto 0);
        C_V_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        C_V_ce0 : OUT STD_LOGIC;
        C_V_q0 : IN STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component mult_hw_A_V_RAM_1WNR_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address2 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address3 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce3 : IN STD_LOGIC;
        q3 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component mult_hw_B_V_RAM_1WNR_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address2 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address3 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce3 : IN STD_LOGIC;
        q3 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component mult_hw_C_V_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (17 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component mult_hw_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        in1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        in2 : OUT STD_LOGIC_VECTOR (63 downto 0);
        out_r : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component mult_hw_gmem_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        USER_RFIFONUM_WIDTH : INTEGER;
        USER_DW : INTEGER;
        USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_ARVALID : IN STD_LOGIC;
        I_ARREADY : OUT STD_LOGIC;
        I_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_RVALID : OUT STD_LOGIC;
        I_RREADY : IN STD_LOGIC;
        I_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_RFIFONUM : OUT STD_LOGIC_VECTOR (8 downto 0);
        I_AWVALID : IN STD_LOGIC;
        I_AWREADY : OUT STD_LOGIC;
        I_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_WVALID : IN STD_LOGIC;
        I_WREADY : OUT STD_LOGIC;
        I_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_BVALID : OUT STD_LOGIC;
        I_BREADY : IN STD_LOGIC );
    end component;



begin
    A_V_U : component mult_hw_A_V_RAM_1WNR_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => A_V_address0,
        ce0 => A_V_ce0,
        we0 => A_V_we0,
        d0 => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_d0,
        q0 => A_V_q0,
        address1 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_address1,
        ce1 => A_V_ce1,
        q1 => A_V_q1,
        address2 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_address2,
        ce2 => A_V_ce2,
        q2 => A_V_q2,
        address3 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_address3,
        ce3 => A_V_ce3,
        q3 => A_V_q3);

    B_V_U : component mult_hw_B_V_RAM_1WNR_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => B_V_address0,
        ce0 => B_V_ce0,
        we0 => B_V_we0,
        d0 => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_d0,
        q0 => B_V_q0,
        address1 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_address1,
        ce1 => B_V_ce1,
        q1 => B_V_q1,
        address2 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_address2,
        ce2 => B_V_ce2,
        q2 => B_V_q2,
        address3 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_address3,
        ce3 => B_V_ce3,
        q3 => B_V_q3);

    C_V_U : component mult_hw_C_V_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => C_V_address0,
        ce0 => C_V_ce0,
        we0 => C_V_we0,
        d0 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_d0,
        q0 => C_V_q0);

    grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108 : component mult_hw_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_start,
        ap_done => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_done,
        ap_idle => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_idle,
        ap_ready => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_ready,
        m_axi_gmem_AWVALID => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY => ap_const_logic_0,
        m_axi_gmem_AWADDR => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWADDR,
        m_axi_gmem_AWID => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWID,
        m_axi_gmem_AWLEN => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_WVALID,
        m_axi_gmem_WREADY => ap_const_logic_0,
        m_axi_gmem_WDATA => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_WLAST,
        m_axi_gmem_WID => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_WID,
        m_axi_gmem_WUSER => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY => gmem_ARREADY,
        m_axi_gmem_ARADDR => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARADDR,
        m_axi_gmem_ARID => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARID,
        m_axi_gmem_ARLEN => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID => gmem_RVALID,
        m_axi_gmem_RREADY => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_RREADY,
        m_axi_gmem_RDATA => gmem_RDATA,
        m_axi_gmem_RLAST => ap_const_logic_0,
        m_axi_gmem_RID => ap_const_lv1_0,
        m_axi_gmem_RFIFONUM => gmem_RFIFONUM,
        m_axi_gmem_RUSER => ap_const_lv1_0,
        m_axi_gmem_RRESP => ap_const_lv2_0,
        m_axi_gmem_BVALID => ap_const_logic_0,
        m_axi_gmem_BREADY => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_BREADY,
        m_axi_gmem_BRESP => ap_const_lv2_0,
        m_axi_gmem_BID => ap_const_lv1_0,
        m_axi_gmem_BUSER => ap_const_lv1_0,
        A_V_address0 => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_address0,
        A_V_ce0 => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_ce0,
        A_V_we0 => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_we0,
        A_V_d0 => grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_d0,
        in1 => in1_read_reg_177,
        trunc_ln => trunc_ln19_reg_182);

    grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119 : component mult_hw_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_start,
        ap_done => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_done,
        ap_idle => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_idle,
        ap_ready => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_ready,
        m_axi_gmem_AWVALID => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY => ap_const_logic_0,
        m_axi_gmem_AWADDR => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWADDR,
        m_axi_gmem_AWID => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWID,
        m_axi_gmem_AWLEN => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_WVALID,
        m_axi_gmem_WREADY => ap_const_logic_0,
        m_axi_gmem_WDATA => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_WLAST,
        m_axi_gmem_WID => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_WID,
        m_axi_gmem_WUSER => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY => gmem_ARREADY,
        m_axi_gmem_ARADDR => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARADDR,
        m_axi_gmem_ARID => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARID,
        m_axi_gmem_ARLEN => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID => gmem_RVALID,
        m_axi_gmem_RREADY => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_RREADY,
        m_axi_gmem_RDATA => gmem_RDATA,
        m_axi_gmem_RLAST => ap_const_logic_0,
        m_axi_gmem_RID => ap_const_lv1_0,
        m_axi_gmem_RFIFONUM => gmem_RFIFONUM,
        m_axi_gmem_RUSER => ap_const_lv1_0,
        m_axi_gmem_RRESP => ap_const_lv2_0,
        m_axi_gmem_BVALID => ap_const_logic_0,
        m_axi_gmem_BREADY => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_BREADY,
        m_axi_gmem_BRESP => ap_const_lv2_0,
        m_axi_gmem_BID => ap_const_lv1_0,
        m_axi_gmem_BUSER => ap_const_lv1_0,
        B_V_address0 => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_address0,
        B_V_ce0 => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_ce0,
        B_V_we0 => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_we0,
        B_V_d0 => grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_d0,
        in2 => in2_read_reg_172,
        trunc_ln1 => trunc_ln26_reg_187);

    grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128 : component mult_hw_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_start,
        ap_done => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_done,
        ap_idle => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_idle,
        ap_ready => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_ready,
        A_V_address0 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_address0,
        A_V_ce0 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce0,
        A_V_q0 => A_V_q0,
        A_V_address1 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_address1,
        A_V_ce1 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce1,
        A_V_q1 => A_V_q1,
        A_V_address2 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_address2,
        A_V_ce2 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce2,
        A_V_q2 => A_V_q2,
        A_V_address3 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_address3,
        A_V_ce3 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce3,
        A_V_q3 => A_V_q3,
        B_V_address0 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_address0,
        B_V_ce0 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce0,
        B_V_q0 => B_V_q0,
        B_V_address1 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_address1,
        B_V_ce1 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce1,
        B_V_q1 => B_V_q1,
        B_V_address2 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_address2,
        B_V_ce2 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce2,
        B_V_q2 => B_V_q2,
        B_V_address3 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_address3,
        B_V_ce3 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce3,
        B_V_q3 => B_V_q3,
        C_V_address0 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_address0,
        C_V_ce0 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_ce0,
        C_V_we0 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_we0,
        C_V_d0 => grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_d0);

    grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135 : component mult_hw_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_start,
        ap_done => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_done,
        ap_idle => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_idle,
        ap_ready => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_ready,
        m_axi_gmem_AWVALID => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY => gmem_AWREADY,
        m_axi_gmem_AWADDR => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWADDR,
        m_axi_gmem_AWID => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWID,
        m_axi_gmem_AWLEN => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WVALID,
        m_axi_gmem_WREADY => gmem_WREADY,
        m_axi_gmem_WDATA => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WLAST,
        m_axi_gmem_WID => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WID,
        m_axi_gmem_WUSER => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY => ap_const_logic_0,
        m_axi_gmem_ARADDR => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARADDR,
        m_axi_gmem_ARID => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARID,
        m_axi_gmem_ARLEN => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID => ap_const_logic_0,
        m_axi_gmem_RREADY => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_RREADY,
        m_axi_gmem_RDATA => ap_const_lv32_0,
        m_axi_gmem_RLAST => ap_const_logic_0,
        m_axi_gmem_RID => ap_const_lv1_0,
        m_axi_gmem_RFIFONUM => ap_const_lv9_0,
        m_axi_gmem_RUSER => ap_const_lv1_0,
        m_axi_gmem_RRESP => ap_const_lv2_0,
        m_axi_gmem_BVALID => gmem_BVALID,
        m_axi_gmem_BREADY => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_BREADY,
        m_axi_gmem_BRESP => ap_const_lv2_0,
        m_axi_gmem_BID => ap_const_lv1_0,
        m_axi_gmem_BUSER => ap_const_lv1_0,
        sext_ln42 => trunc_ln2_reg_192,
        C_V_address0 => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_C_V_address0,
        C_V_ce0 => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_C_V_ce0,
        C_V_q0 => C_V_q0);

    control_s_axi_U : component mult_hw_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        in1 => in1,
        in2 => in2,
        out_r => out_r);

    gmem_m_axi_U : component mult_hw_gmem_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 5,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM_CACHE_VALUE,
        USER_RFIFONUM_WIDTH => 9,
        USER_DW => 32,
        USER_AW => 64,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 16)
    port map (
        AWVALID => m_axi_gmem_AWVALID,
        AWREADY => m_axi_gmem_AWREADY,
        AWADDR => m_axi_gmem_AWADDR,
        AWID => m_axi_gmem_AWID,
        AWLEN => m_axi_gmem_AWLEN,
        AWSIZE => m_axi_gmem_AWSIZE,
        AWBURST => m_axi_gmem_AWBURST,
        AWLOCK => m_axi_gmem_AWLOCK,
        AWCACHE => m_axi_gmem_AWCACHE,
        AWPROT => m_axi_gmem_AWPROT,
        AWQOS => m_axi_gmem_AWQOS,
        AWREGION => m_axi_gmem_AWREGION,
        AWUSER => m_axi_gmem_AWUSER,
        WVALID => m_axi_gmem_WVALID,
        WREADY => m_axi_gmem_WREADY,
        WDATA => m_axi_gmem_WDATA,
        WSTRB => m_axi_gmem_WSTRB,
        WLAST => m_axi_gmem_WLAST,
        WID => m_axi_gmem_WID,
        WUSER => m_axi_gmem_WUSER,
        ARVALID => m_axi_gmem_ARVALID,
        ARREADY => m_axi_gmem_ARREADY,
        ARADDR => m_axi_gmem_ARADDR,
        ARID => m_axi_gmem_ARID,
        ARLEN => m_axi_gmem_ARLEN,
        ARSIZE => m_axi_gmem_ARSIZE,
        ARBURST => m_axi_gmem_ARBURST,
        ARLOCK => m_axi_gmem_ARLOCK,
        ARCACHE => m_axi_gmem_ARCACHE,
        ARPROT => m_axi_gmem_ARPROT,
        ARQOS => m_axi_gmem_ARQOS,
        ARREGION => m_axi_gmem_ARREGION,
        ARUSER => m_axi_gmem_ARUSER,
        RVALID => m_axi_gmem_RVALID,
        RREADY => m_axi_gmem_RREADY,
        RDATA => m_axi_gmem_RDATA,
        RLAST => m_axi_gmem_RLAST,
        RID => m_axi_gmem_RID,
        RUSER => m_axi_gmem_RUSER,
        RRESP => m_axi_gmem_RRESP,
        BVALID => m_axi_gmem_BVALID,
        BREADY => m_axi_gmem_BREADY,
        BRESP => m_axi_gmem_BRESP,
        BID => m_axi_gmem_BID,
        BUSER => m_axi_gmem_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_ARVALID => gmem_ARVALID,
        I_ARREADY => gmem_ARREADY,
        I_ARADDR => gmem_ARADDR,
        I_ARLEN => gmem_ARLEN,
        I_RVALID => gmem_RVALID,
        I_RREADY => gmem_RREADY,
        I_RDATA => gmem_RDATA,
        I_RFIFONUM => gmem_RFIFONUM,
        I_AWVALID => gmem_AWVALID,
        I_AWREADY => gmem_AWREADY,
        I_AWADDR => gmem_AWADDR,
        I_AWLEN => gmem_AWLEN,
        I_WVALID => gmem_WVALID,
        I_WREADY => gmem_WREADY,
        I_WDATA => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WDATA,
        I_WSTRB => grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WSTRB,
        I_BVALID => gmem_BVALID,
        I_BREADY => gmem_BREADY);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_ready = ap_const_logic_1)) then 
                    grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_ready = ap_const_logic_1)) then 
                    grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_ready = ap_const_logic_1)) then 
                    grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_ready = ap_const_logic_1)) then 
                    grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                in1_read_reg_177 <= in1;
                in2_read_reg_172 <= in2;
                trunc_ln19_reg_182 <= trunc_ln19_fu_143_p1;
                trunc_ln26_reg_187 <= trunc_ln26_fu_148_p1;
                trunc_ln2_reg_192 <= out_r(63 downto 2);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state6, ap_CS_fsm_state13, grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_done, grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_done, grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_done, grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_done, gmem_AWREADY, gmem_BVALID, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if ((not(((gmem_AWREADY = ap_const_logic_0) or (grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                if (((gmem_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXX";
        end case;
    end process;

    A_V_address0_assign_proc : process(ap_CS_fsm_state6, grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_address0, grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_address0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            A_V_address0 <= grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            A_V_address0 <= grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_address0;
        else 
            A_V_address0 <= "XXXXX";
        end if; 
    end process;


    A_V_ce0_assign_proc : process(ap_CS_fsm_state6, grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_ce0, grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            A_V_ce0 <= grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            A_V_ce0 <= grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_ce0;
        else 
            A_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    A_V_ce1_assign_proc : process(ap_CS_fsm_state6, grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            A_V_ce1 <= grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce1;
        else 
            A_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    A_V_ce2_assign_proc : process(ap_CS_fsm_state6, grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            A_V_ce2 <= grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce2;
        else 
            A_V_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    A_V_ce3_assign_proc : process(ap_CS_fsm_state6, grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            A_V_ce3 <= grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce3;
        else 
            A_V_ce3 <= ap_const_logic_0;
        end if; 
    end process;


    A_V_we0_assign_proc : process(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            A_V_we0 <= grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_we0;
        else 
            A_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    B_V_address0_assign_proc : process(ap_CS_fsm_state6, grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_address0, grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_address0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            B_V_address0 <= grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            B_V_address0 <= grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_address0;
        else 
            B_V_address0 <= "XXXXXX";
        end if; 
    end process;


    B_V_ce0_assign_proc : process(ap_CS_fsm_state6, grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_ce0, grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            B_V_ce0 <= grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            B_V_ce0 <= grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_ce0;
        else 
            B_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    B_V_ce1_assign_proc : process(ap_CS_fsm_state6, grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            B_V_ce1 <= grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce1;
        else 
            B_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    B_V_ce2_assign_proc : process(ap_CS_fsm_state6, grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            B_V_ce2 <= grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce2;
        else 
            B_V_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    B_V_ce3_assign_proc : process(ap_CS_fsm_state6, grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            B_V_ce3 <= grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce3;
        else 
            B_V_ce3 <= ap_const_logic_0;
        end if; 
    end process;


    B_V_we0_assign_proc : process(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            B_V_we0 <= grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_we0;
        else 
            B_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    C_V_address0_assign_proc : process(ap_CS_fsm_state6, grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_address0, grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_C_V_address0, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            C_V_address0 <= grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_C_V_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            C_V_address0 <= grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_address0;
        else 
            C_V_address0 <= "XXXXXXX";
        end if; 
    end process;


    C_V_ce0_assign_proc : process(ap_CS_fsm_state6, grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_ce0, grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_C_V_ce0, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            C_V_ce0 <= grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_C_V_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            C_V_ce0 <= grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_ce0;
        else 
            C_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    C_V_we0_assign_proc : process(ap_CS_fsm_state6, grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_we0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            C_V_we0 <= grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_we0;
        else 
            C_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;

    ap_ST_fsm_state13_blk_assign_proc : process(gmem_BVALID)
    begin
        if ((gmem_BVALID = ap_const_logic_0)) then 
            ap_ST_fsm_state13_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state13_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_done)
    begin
        if ((grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_done)
    begin
        if ((grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_done, gmem_AWREADY)
    begin
        if (((gmem_AWREADY = ap_const_logic_0) or (grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_done = ap_const_logic_0))) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_done)
    begin
        if ((grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state13, gmem_BVALID)
    begin
        if (((gmem_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state13, gmem_BVALID)
    begin
        if (((gmem_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    gmem_ARADDR_assign_proc : process(ap_CS_fsm_state1, grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARADDR, grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARADDR, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            gmem_ARADDR <= grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARADDR;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            gmem_ARADDR <= grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARADDR;
        else 
            gmem_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    gmem_ARLEN_assign_proc : process(ap_CS_fsm_state1, grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARLEN, grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARLEN, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            gmem_ARLEN <= grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARLEN;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            gmem_ARLEN <= grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARLEN;
        else 
            gmem_ARLEN <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    gmem_ARVALID_assign_proc : process(ap_CS_fsm_state1, grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARVALID, grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARVALID, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            gmem_ARVALID <= grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARVALID;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            gmem_ARVALID <= grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARVALID;
        else 
            gmem_ARVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem_AWADDR_assign_proc : process(ap_CS_fsm_state6, grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_done, grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWADDR, gmem_AWREADY, ap_CS_fsm_state7, ap_CS_fsm_state8, sext_ln42_fu_162_p1)
    begin
        if ((not(((gmem_AWREADY = ap_const_logic_0) or (grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            gmem_AWADDR <= sext_ln42_fu_162_p1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            gmem_AWADDR <= grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWADDR;
        else 
            gmem_AWADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    gmem_AWLEN_assign_proc : process(ap_CS_fsm_state6, grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_done, grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWLEN, gmem_AWREADY, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if ((not(((gmem_AWREADY = ap_const_logic_0) or (grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            gmem_AWLEN <= ap_const_lv32_80;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            gmem_AWLEN <= grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWLEN;
        else 
            gmem_AWLEN <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    gmem_AWVALID_assign_proc : process(ap_CS_fsm_state6, grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_done, grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWVALID, gmem_AWREADY, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if ((not(((gmem_AWREADY = ap_const_logic_0) or (grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            gmem_AWVALID <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            gmem_AWVALID <= grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWVALID;
        else 
            gmem_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem_BREADY_assign_proc : process(ap_CS_fsm_state13, grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_BREADY, gmem_BVALID, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if (((gmem_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            gmem_BREADY <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            gmem_BREADY <= grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_BREADY;
        else 
            gmem_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    gmem_RREADY_assign_proc : process(ap_CS_fsm_state1, grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_RREADY, grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_RREADY, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            gmem_RREADY <= grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_RREADY;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            gmem_RREADY <= grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_RREADY;
        else 
            gmem_RREADY <= ap_const_logic_0;
        end if; 
    end process;


    gmem_WVALID_assign_proc : process(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WVALID, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            gmem_WVALID <= grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WVALID;
        else 
            gmem_WVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem_blk_n_AW_assign_proc : process(m_axi_gmem_AWREADY, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            gmem_blk_n_AW <= m_axi_gmem_AWREADY;
        else 
            gmem_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    gmem_blk_n_B_assign_proc : process(m_axi_gmem_BVALID, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            gmem_blk_n_B <= m_axi_gmem_BVALID;
        else 
            gmem_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;

    grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_start <= grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_start_reg;
    grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_start <= grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_start_reg;
    grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_start <= grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_start_reg;
    grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_start <= grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_start_reg;
        sext_ln42_fu_162_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln2_reg_192),64));

    trunc_ln19_fu_143_p1 <= in1(2 - 1 downto 0);
    trunc_ln26_fu_148_p1 <= in2(2 - 1 downto 0);
end behav;
