// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mult_hw_mult_hw,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu200-fsgd2104-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=392,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1994,HLS_SYN_LUT=3293,HLS_VERSION=2022_2}" *)

module mult_hw (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 13'd1;
parameter    ap_ST_fsm_state2 = 13'd2;
parameter    ap_ST_fsm_state3 = 13'd4;
parameter    ap_ST_fsm_state4 = 13'd8;
parameter    ap_ST_fsm_state5 = 13'd16;
parameter    ap_ST_fsm_state6 = 13'd32;
parameter    ap_ST_fsm_state7 = 13'd64;
parameter    ap_ST_fsm_state8 = 13'd128;
parameter    ap_ST_fsm_state9 = 13'd256;
parameter    ap_ST_fsm_state10 = 13'd512;
parameter    ap_ST_fsm_state11 = 13'd1024;
parameter    ap_ST_fsm_state12 = 13'd2048;
parameter    ap_ST_fsm_state13 = 13'd4096;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [12:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [63:0] in1;
wire   [63:0] in2;
wire   [63:0] out_r;
reg    gmem_blk_n_AW;
wire    ap_CS_fsm_state6;
reg    gmem_blk_n_B;
wire    ap_CS_fsm_state13;
reg   [63:0] in2_read_reg_172;
reg   [63:0] in1_read_reg_177;
wire   [1:0] trunc_ln19_fu_143_p1;
reg   [1:0] trunc_ln19_reg_182;
wire   [1:0] trunc_ln26_fu_148_p1;
reg   [1:0] trunc_ln26_reg_187;
reg   [61:0] trunc_ln2_reg_192;
reg   [4:0] A_V_address0;
reg    A_V_ce0;
reg    A_V_we0;
wire   [7:0] A_V_q0;
reg    A_V_ce1;
wire   [7:0] A_V_q1;
reg    A_V_ce2;
wire   [7:0] A_V_q2;
reg    A_V_ce3;
wire   [7:0] A_V_q3;
reg   [5:0] B_V_address0;
reg    B_V_ce0;
reg    B_V_we0;
wire   [7:0] B_V_q0;
reg    B_V_ce1;
wire   [7:0] B_V_q1;
reg    B_V_ce2;
wire   [7:0] B_V_q2;
reg    B_V_ce3;
wire   [7:0] B_V_q3;
reg   [6:0] C_V_address0;
reg    C_V_ce0;
reg    C_V_we0;
wire   [17:0] C_V_q0;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_start;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_done;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_idle;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_ready;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWVALID;
wire   [63:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWADDR;
wire   [0:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWID;
wire   [31:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWLEN;
wire   [2:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWSIZE;
wire   [1:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWBURST;
wire   [1:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWLOCK;
wire   [3:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWCACHE;
wire   [2:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWPROT;
wire   [3:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWQOS;
wire   [3:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWREGION;
wire   [0:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWUSER;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_WVALID;
wire   [31:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_WDATA;
wire   [3:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_WSTRB;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_WLAST;
wire   [0:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_WID;
wire   [0:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_WUSER;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARVALID;
wire   [63:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARADDR;
wire   [0:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARID;
wire   [31:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARLEN;
wire   [2:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARSIZE;
wire   [1:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARBURST;
wire   [1:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARLOCK;
wire   [3:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARCACHE;
wire   [2:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARPROT;
wire   [3:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARQOS;
wire   [3:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARREGION;
wire   [0:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARUSER;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_RREADY;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_BREADY;
wire   [4:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_address0;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_ce0;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_we0;
wire   [7:0] grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_d0;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_start;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_done;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_idle;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_ready;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWVALID;
wire   [63:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWADDR;
wire   [0:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWID;
wire   [31:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWLEN;
wire   [2:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWSIZE;
wire   [1:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWBURST;
wire   [1:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWLOCK;
wire   [3:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWCACHE;
wire   [2:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWPROT;
wire   [3:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWQOS;
wire   [3:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWREGION;
wire   [0:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWUSER;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_WVALID;
wire   [31:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_WDATA;
wire   [3:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_WSTRB;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_WLAST;
wire   [0:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_WID;
wire   [0:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_WUSER;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARVALID;
wire   [63:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARADDR;
wire   [0:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARID;
wire   [31:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARLEN;
wire   [2:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARSIZE;
wire   [1:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARBURST;
wire   [1:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARLOCK;
wire   [3:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARCACHE;
wire   [2:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARPROT;
wire   [3:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARQOS;
wire   [3:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARREGION;
wire   [0:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARUSER;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_RREADY;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_BREADY;
wire   [5:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_address0;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_ce0;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_we0;
wire   [7:0] grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_d0;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_start;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_done;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_idle;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_ready;
wire   [4:0] grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_address0;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce0;
wire   [4:0] grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_address1;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce1;
wire   [4:0] grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_address2;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce2;
wire   [4:0] grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_address3;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce3;
wire   [5:0] grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_address0;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce0;
wire   [5:0] grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_address1;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce1;
wire   [5:0] grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_address2;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce2;
wire   [5:0] grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_address3;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce3;
wire   [6:0] grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_address0;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_ce0;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_we0;
wire   [17:0] grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_d0;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_start;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_done;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_idle;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_ready;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWVALID;
wire   [63:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWADDR;
wire   [0:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWID;
wire   [31:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWLEN;
wire   [2:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWSIZE;
wire   [1:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWBURST;
wire   [1:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWLOCK;
wire   [3:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWCACHE;
wire   [2:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWPROT;
wire   [3:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWQOS;
wire   [3:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWREGION;
wire   [0:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWUSER;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WVALID;
wire   [31:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WDATA;
wire   [3:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WSTRB;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WLAST;
wire   [0:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WID;
wire   [0:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WUSER;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARVALID;
wire   [63:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARADDR;
wire   [0:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARID;
wire   [31:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARLEN;
wire   [2:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARSIZE;
wire   [1:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARBURST;
wire   [1:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARLOCK;
wire   [3:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARCACHE;
wire   [2:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARPROT;
wire   [3:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARQOS;
wire   [3:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARREGION;
wire   [0:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARUSER;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_RREADY;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_BREADY;
wire   [6:0] grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_C_V_address0;
wire    grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_C_V_ce0;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
reg   [63:0] gmem_AWADDR;
reg   [31:0] gmem_AWLEN;
reg    gmem_WVALID;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
reg   [63:0] gmem_ARADDR;
reg   [31:0] gmem_ARLEN;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [31:0] gmem_RDATA;
wire   [8:0] gmem_RFIFONUM;
wire    gmem_BVALID;
reg    gmem_BREADY;
reg    grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire  signed [63:0] sext_ln42_fu_162_p1;
reg   [12:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 13'd1;
#0 grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_start_reg = 1'b0;
#0 grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_start_reg = 1'b0;
#0 grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_start_reg = 1'b0;
#0 grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_start_reg = 1'b0;
end

mult_hw_A_V_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
A_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_V_address0),
    .ce0(A_V_ce0),
    .we0(A_V_we0),
    .d0(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_d0),
    .q0(A_V_q0),
    .address1(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_address1),
    .ce1(A_V_ce1),
    .q1(A_V_q1),
    .address2(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_address2),
    .ce2(A_V_ce2),
    .q2(A_V_q2),
    .address3(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_address3),
    .ce3(A_V_ce3),
    .q3(A_V_q3)
);

mult_hw_B_V_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
B_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(B_V_address0),
    .ce0(B_V_ce0),
    .we0(B_V_we0),
    .d0(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_d0),
    .q0(B_V_q0),
    .address1(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_address1),
    .ce1(B_V_ce1),
    .q1(B_V_q1),
    .address2(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_address2),
    .ce2(B_V_ce2),
    .q2(B_V_q2),
    .address3(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_address3),
    .ce3(B_V_ce3),
    .q3(B_V_q3)
);

mult_hw_C_V_RAM_AUTO_1R1W #(
    .DataWidth( 18 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
C_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(C_V_address0),
    .ce0(C_V_ce0),
    .we0(C_V_we0),
    .d0(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_d0),
    .q0(C_V_q0)
);

mult_hw_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2 grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_start),
    .ap_done(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_done),
    .ap_idle(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_idle),
    .ap_ready(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_ready),
    .m_axi_gmem_AWVALID(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .A_V_address0(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_address0),
    .A_V_ce0(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_ce0),
    .A_V_we0(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_we0),
    .A_V_d0(grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_d0),
    .in1(in1_read_reg_177),
    .trunc_ln(trunc_ln19_reg_182)
);

mult_hw_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4 grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_start),
    .ap_done(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_done),
    .ap_idle(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_idle),
    .ap_ready(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_ready),
    .m_axi_gmem_AWVALID(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .B_V_address0(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_address0),
    .B_V_ce0(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_ce0),
    .B_V_we0(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_we0),
    .B_V_d0(grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_d0),
    .in2(in2_read_reg_172),
    .trunc_ln1(trunc_ln26_reg_187)
);

mult_hw_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6 grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_start),
    .ap_done(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_done),
    .ap_idle(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_idle),
    .ap_ready(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_ready),
    .A_V_address0(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_address0),
    .A_V_ce0(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce0),
    .A_V_q0(A_V_q0),
    .A_V_address1(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_address1),
    .A_V_ce1(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce1),
    .A_V_q1(A_V_q1),
    .A_V_address2(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_address2),
    .A_V_ce2(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce2),
    .A_V_q2(A_V_q2),
    .A_V_address3(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_address3),
    .A_V_ce3(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce3),
    .A_V_q3(A_V_q3),
    .B_V_address0(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_address0),
    .B_V_ce0(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce0),
    .B_V_q0(B_V_q0),
    .B_V_address1(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_address1),
    .B_V_ce1(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce1),
    .B_V_q1(B_V_q1),
    .B_V_address2(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_address2),
    .B_V_ce2(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce2),
    .B_V_q2(B_V_q2),
    .B_V_address3(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_address3),
    .B_V_ce3(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce3),
    .B_V_q3(B_V_q3),
    .C_V_address0(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_address0),
    .C_V_ce0(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_ce0),
    .C_V_we0(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_we0),
    .C_V_d0(grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_d0)
);

mult_hw_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9 grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_start),
    .ap_done(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_done),
    .ap_idle(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_idle),
    .ap_ready(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_ready),
    .m_axi_gmem_AWVALID(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(gmem_AWREADY),
    .m_axi_gmem_AWADDR(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(gmem_WREADY),
    .m_axi_gmem_WDATA(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(1'b0),
    .m_axi_gmem_ARADDR(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(1'b0),
    .m_axi_gmem_RREADY(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(32'd0),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(9'd0),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(gmem_BVALID),
    .m_axi_gmem_BREADY(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .sext_ln42(trunc_ln2_reg_192),
    .C_V_address0(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_C_V_address0),
    .C_V_ce0(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_C_V_ce0),
    .C_V_q0(C_V_q0)
);

mult_hw_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .in1(in1),
    .in2(in2),
    .out_r(out_r)
);

mult_hw_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(gmem_ARADDR),
    .I_ARLEN(gmem_ARLEN),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RFIFONUM(gmem_RFIFONUM),
    .I_AWVALID(gmem_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(gmem_AWADDR),
    .I_AWLEN(gmem_AWLEN),
    .I_WVALID(gmem_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WDATA),
    .I_WSTRB(grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WSTRB),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(gmem_BREADY)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_start_reg <= 1'b1;
        end else if ((grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_ready == 1'b1)) begin
            grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_start_reg <= 1'b1;
        end else if ((grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_ready == 1'b1)) begin
            grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_start_reg <= 1'b1;
        end else if ((grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_ready == 1'b1)) begin
            grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_start_reg <= 1'b1;
        end else if ((grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_ready == 1'b1)) begin
            grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        in1_read_reg_177 <= in1;
        in2_read_reg_172 <= in2;
        trunc_ln19_reg_182 <= trunc_ln19_fu_143_p1;
        trunc_ln26_reg_187 <= trunc_ln26_fu_148_p1;
        trunc_ln2_reg_192 <= {{out_r[63:2]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_V_address0 = grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        A_V_address0 = grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_address0;
    end else begin
        A_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_V_ce0 = grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        A_V_ce0 = grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_ce0;
    end else begin
        A_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_V_ce1 = grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce1;
    end else begin
        A_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_V_ce2 = grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce2;
    end else begin
        A_V_ce2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_V_ce3 = grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_A_V_ce3;
    end else begin
        A_V_ce3 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        A_V_we0 = grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_A_V_we0;
    end else begin
        A_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B_V_address0 = grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        B_V_address0 = grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_address0;
    end else begin
        B_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B_V_ce0 = grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        B_V_ce0 = grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_ce0;
    end else begin
        B_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B_V_ce1 = grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce1;
    end else begin
        B_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B_V_ce2 = grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce2;
    end else begin
        B_V_ce2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B_V_ce3 = grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_B_V_ce3;
    end else begin
        B_V_ce3 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        B_V_we0 = grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_B_V_we0;
    end else begin
        B_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        C_V_address0 = grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_C_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        C_V_address0 = grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_address0;
    end else begin
        C_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        C_V_ce0 = grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_C_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        C_V_ce0 = grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_ce0;
    end else begin
        C_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        C_V_we0 = grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_C_V_we0;
    end else begin
        C_V_we0 = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((gmem_BVALID == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((gmem_AWREADY == 1'b0) | (grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_done == 1'b0))) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        gmem_ARADDR = grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        gmem_ARADDR = grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARADDR;
    end else begin
        gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        gmem_ARLEN = grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        gmem_ARLEN = grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARLEN;
    end else begin
        gmem_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        gmem_ARVALID = grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        gmem_ARVALID = grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_ARVALID;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((gmem_AWREADY == 1'b0) | (grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
        gmem_AWADDR = sext_ln42_fu_162_p1;
    end else if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        gmem_AWADDR = grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWADDR;
    end else begin
        gmem_AWADDR = 'bx;
    end
end

always @ (*) begin
    if ((~((gmem_AWREADY == 1'b0) | (grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
        gmem_AWLEN = 32'd128;
    end else if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        gmem_AWLEN = grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWLEN;
    end else begin
        gmem_AWLEN = 'bx;
    end
end

always @ (*) begin
    if ((~((gmem_AWREADY == 1'b0) | (grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
        gmem_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        gmem_AWVALID = grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_AWVALID;
    end else begin
        gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        gmem_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        gmem_BREADY = grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_BREADY;
    end else begin
        gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        gmem_RREADY = grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_m_axi_gmem_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        gmem_RREADY = grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_m_axi_gmem_RREADY;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        gmem_WVALID = grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_m_axi_gmem_WVALID;
    end else begin
        gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if ((~((gmem_AWREADY == 1'b0) | (grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_start = grp_mult_hw_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_108_ap_start_reg;

assign grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_start = grp_mult_hw_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4_fu_119_ap_start_reg;

assign grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_start = grp_mult_hw_Pipeline_VITIS_LOOP_31_5_VITIS_LOOP_32_6_fu_128_ap_start_reg;

assign grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_start = grp_mult_hw_Pipeline_VITIS_LOOP_42_8_VITIS_LOOP_43_9_fu_135_ap_start_reg;

assign sext_ln42_fu_162_p1 = $signed(trunc_ln2_reg_192);

assign trunc_ln19_fu_143_p1 = in1[1:0];

assign trunc_ln26_fu_148_p1 = in2[1:0];

endmodule //mult_hw
